name: Build PlayAsGobo

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
  workflow_dispatch:

jobs:
  build-windows:
    name: Build on Windows
    runs-on: windows-latest
    
    strategy:
      matrix:
        build_type: [Debug, Release]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: UCRT64
        update: true
        install: >-
          mingw-w64-ucrt-x86_64-gcc
          mingw-w64-ucrt-x86_64-cmake
          mingw-w64-ucrt-x86_64-ninja
          mingw-w64-ucrt-x86_64-pkgconf
    
    - name: Configure CMake (MSYS2)
      shell: msys2 {0}
      run: |
        cmake -B build -G Ninja \
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
          -DCMAKE_C_COMPILER=gcc \
          -DCMAKE_CXX_COMPILER=g++
    
    - name: Build
      shell: msys2 {0}
      run: cmake --build build --config ${{ matrix.build_type }}
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: PlayAsGobo-Windows-${{ matrix.build_type }}
        path: |
          bin/${{ matrix.build_type }}/PlayAsGobo.exe
          bin/${{ matrix.build_type }}/assets/
        retention-days: 7

  build-linux:
    name: Build on Linux
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        build_type: [Debug, Release]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake \
          ninja-build \
          libx11-dev \
          libxrandr-dev \
          libxi-dev \
          libxcursor-dev \
          libxinerama-dev \
          libgl1-mesa-dev \
          libasound2-dev \
          pkg-config
    
    - name: Configure CMake
      run: |
        cmake -B build -G Ninja \
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
    
    - name: Build
      run: cmake --build build --config ${{ matrix.build_type }}
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: PlayAsGobo-Linux-${{ matrix.build_type }}
        path: |
          bin/${{ matrix.build_type }}/PlayAsGobo
          bin/${{ matrix.build_type }}/assets/
        retention-days: 7

  build-macos:
    name: Build on macOS
    runs-on: macos-latest
    
    strategy:
      matrix:
        build_type: [Debug, Release]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Install dependencies
      run: |
        brew install cmake ninja pkg-config
    
    - name: Configure CMake
      run: |
        cmake -B build -G Ninja \
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
    
    - name: Build
      run: cmake --build build --config ${{ matrix.build_type }}
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: PlayAsGobo-macOS-${{ matrix.build_type }}
        path: |
          bin/${{ matrix.build_type }}/PlayAsGobo.app
          bin/${{ matrix.build_type }}/assets/
        retention-days: 7

  create-release:
    name: Create Release Package
    needs: [build-windows, build-linux, build-macos]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
    
    - name: Create release archives
      run: |
        # Windows Release
        cd PlayAsGobo-Windows-Release
        zip -r ../PlayAsGobo-Windows-Release.zip .
        cd ..
        
        # Linux Release
        cd PlayAsGobo-Linux-Release
        tar -czf ../PlayAsGobo-Linux-Release.tar.gz .
        cd ..
        
        # macOS Release
        cd PlayAsGobo-macOS-Release
        zip -r ../PlayAsGobo-macOS-Release.zip .
        cd ..
    
    - name: Upload release packages
      uses: actions/upload-artifact@v4
      with:
        name: Release-Packages
        path: |
          PlayAsGobo-Windows-Release.zip
          PlayAsGobo-Linux-Release.tar.gz
          PlayAsGobo-macOS-Release.zip
        retention-days: 30